version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    #tengo que mapear únicamente los volúmenes
    volumes:
      - /home/ricardo/lm/docker-study/recipe-09/php:/var/www/myapp
      - /home/ricardo/lm/docker-study/recipe-09/docker/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  php:
    build: php-xdebug-custom
    volumes:
      #tengo que mapear únicamente los volúmenes
      - /home/ricardo/lm/docker-study/recipe-09/php:/var/www/myapp
      - /home/ricardo/lm/docker-study/recipe-09/docker/php.ini:/usr/local/etc/php/php.ini
